#!/bin/zsh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT="$ROOT/firmware/src/fonts/jetbrains_mono_ascii_8.h"
TMP_DIR="$(mktemp -d /tmp/code-buddy-font.XXXXXX)"
trap 'find "$TMP_DIR" -type f -delete; find "$TMP_DIR" -depth -type d -exec rmdir {} +' EXIT

FONT_URL="https://raw.githubusercontent.com/JetBrains/JetBrainsMono/v2.304/fonts/ttf/JetBrainsMono-Regular.ttf"
FONT_SHA256="a0bf60ef0f83c5ed4d7a75d45838548b1f6873372dfac88f71804491898d138f"
ADAFRUIT_COMMIT="ac6d7c3869a693d406f77b9bfcd486b0673169f0"
CONVERTER_URL="https://raw.githubusercontent.com/adafruit/Adafruit-GFX-Library/$ADAFRUIT_COMMIT/fontconvert/fontconvert.c"
CONVERTER_SHA256="42e70906d68e4a7bced1c47a7bb12d2a86c29484eeb564f76449ea7a9b6c3ba1"
GFXFONT_URL="https://raw.githubusercontent.com/adafruit/Adafruit-GFX-Library/$ADAFRUIT_COMMIT/gfxfont.h"
GFXFONT_SHA256="4e1b06371217d63102bac242d4a3ec8dcaff93cd34b4241bbc39eda521a1be11"

curl -fsSL "$FONT_URL" -o "$TMP_DIR/JetBrainsMono-Regular.ttf"
mkdir -p "$TMP_DIR/fontconvert"
curl -fsSL "$CONVERTER_URL" -o "$TMP_DIR/fontconvert/fontconvert.c"
curl -fsSL "$GFXFONT_URL" -o "$TMP_DIR/gfxfont.h"

verify_sha256() {
  local expected="$1"
  local file_path="$2"
  local actual="$(shasum -a 256 "$file_path" | awk '{print $1}')"
  if [[ "$actual" != "$expected" ]]; then
    print -u2 "SHA-256 mismatch for $file_path: expected $expected, got $actual"
    exit 1
  fi
}

verify_sha256 "$FONT_SHA256" "$TMP_DIR/JetBrainsMono-Regular.ttf"
verify_sha256 "$CONVERTER_SHA256" "$TMP_DIR/fontconvert/fontconvert.c"
verify_sha256 "$GFXFONT_SHA256" "$TMP_DIR/gfxfont.h"

cc "$TMP_DIR/fontconvert/fontconvert.c" $(pkg-config --cflags --libs freetype2) \
  -o "$TMP_DIR/fontconvert-bin"
"$TMP_DIR/fontconvert-bin" "$TMP_DIR/JetBrainsMono-Regular.ttf" 8 32 126 \
  > "$TMP_DIR/generated.h"

mkdir -p "${OUTPUT:h}"
{
  print '#pragma once'
  print ''
  print '#include <M5Unified.h>'
  print ''
  print '// JetBrains Mono Regular v2.304, ASCII U+0020-U+007E, 8 pt.'
  print '// Generated by scripts/generate-jetbrains-mono-font.sh.'
  print '// Licensed under firmware/licenses/JetBrainsMono-OFL.txt.'
  print 'namespace code_buddy_fonts {'
  sed \
    -e 's/^const uint8_t /static const uint8_t /' \
    -e 's/^const GFXglyph /static const lgfx::GFXglyph /' \
    -e 's/^const GFXfont /static const lgfx::GFXfont /' \
    -e 's/(GFXglyph \*)/(lgfx::GFXglyph *)/' \
    "$TMP_DIR/generated.h"
  print '}  // namespace code_buddy_fonts'
} > "$OUTPUT.tmp"
mv "$OUTPUT.tmp" "$OUTPUT"

echo "$OUTPUT"
